<?php

namespace AppBundle\Repository;

/**
 * basdaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class basdaiRepository extends \Doctrine\ORM\EntityRepository
{
}
