<?php

namespace AppBundle\Repository;

/**
 * basdaiReponsesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class basdaiReponsesRepository extends \Doctrine\ORM\EntityRepository
{
}
