<?php

namespace AppBundle\Repository;

/**
 * basfiReponsesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class basfiReponsesRepository extends \Doctrine\ORM\EntityRepository
{
}
