<?php

namespace AppBundle\Repository;

/**
 * basfiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class basfiRepository extends \Doctrine\ORM\EntityRepository
{
}
