<?php

namespace AppBundle\Repository;

/**
 * categoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoriesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getCategoryById($id){
        $qb = $this->createQueryBuilder('category');

        $qb ->where('category.id = :category')
            ->setParameter('category', $id);

        return $qb
            ->getQuery()
            ->getSingleResult();
    }
}
