<?php

namespace AppBundle\Repository;

/**
 * couleursSellesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class couleursSellesRepository extends \Doctrine\ORM\EntityRepository
{
}
