<?php

namespace AppBundle\Repository;

/**
 * douleursUrinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class douleursUrinaireRepository extends \Doctrine\ORM\EntityRepository
{
}
