<?php

namespace AppBundle\Repository;

/**
 * douleursAbdosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class douleursAbdosRepository extends \Doctrine\ORM\EntityRepository
{
}
