<?php

namespace AppBundle\Repository;

/**
 * douleursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class douleursRepository extends \Doctrine\ORM\EntityRepository
{
}
