<?php

namespace AppBundle\Repository;

/**
 * formesSellesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class formesSellesRepository extends \Doctrine\ORM\EntityRepository
{
}
