<?php

namespace AppBundle\Repository;

/**
 * frequenceJournaliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class frequenceJournaliereRepository extends \Doctrine\ORM\EntityRepository
{
}
