<?php

namespace AppBundle\Repository;

/**
 * hematurieMacroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hematurieMacroRepository extends \Doctrine\ORM\EntityRepository
{
}
