<?php

namespace AppBundle\Repository;

/**
 * hematurieMicroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hematurieMicroRepository extends \Doctrine\ORM\EntityRepository
{
}
