<?php

namespace AppBundle\Repository;

/**
 * marqueursBiologiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marqueursBiologiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
