<?php

namespace AppBundle\Repository\Entity;

/**
 * paramVitauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paramVitauxRepository extends \Doctrine\ORM\EntityRepository
{
}
