<?php

namespace AppBundle\Repository;

/**
 * qualificatifSellesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qualificatifSellesRepository extends \Doctrine\ORM\EntityRepository
{
}
