<?php

namespace AppBundle\Repository;

/**
 * traitementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traitementsRepository extends \Doctrine\ORM\EntityRepository
{
}
