<?php

namespace AppBundle\Repository;

/**
 * troublesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class troublesRepository extends \Doctrine\ORM\EntityRepository
{
}
