<?php

namespace AppBundle\Repository;

/**
 * urinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class urinaireRepository extends \Doctrine\ORM\EntityRepository
{
}
